### ISSUE TITLE
Multiplay service link broken

### ISSUE THREAD

**Issue by Chizaruu** [Unity-Technologies/com.unity.services.samples.matchplay#27]
https://github.com/Unity-Technologies/com.unity.services.samples.matchplay#multiplay

![image](https://user-images.githubusercontent.com/59434446/227801116-d60a6956-ca5a-4bf4-a019-f1a3a06c6ecf.png)

![image](https://user-images.githubusercontent.com/59434446/227801152-0e007fb9-11ea-40ba-9c18-7d831f204648.png)

**Comment by UnityJacob** [comment]
Thanks for letting me know! It has been updated with the new link!
