### ISSUE TITLE
Cannot Build in Android

### ISSUE THREAD

**Issue by ZeusK10** [Unity-Technologies/com.unity.services.samples.matchplay#28]
I can build without any issues in windows but when I try to build in android, I get this   **error CS0234: The type or namespace name 'Multiplay' does not exist in the namespace 'Unity.Services' (are you missing an assembly reference?)**

**Comment by UnityJacob** [comment]
So the Multiplay SDK is probably not available for android. This can be worked around as the Multiplay SDK only should be running on Linux Servers on the Game Server hosting service. If you can ensure that no client code references code with "using Unity.Services.Multiplay" etc, and cleanly seperate the server and client code bases, you should be able to build Android clients with no issue.

**Comment by UnityJacob** [comment]
If there are more people experiencing this issue, I can make a work item to update the sample to cleanly separate the builds.

**Comment by ZeusK10** [comment]
It works like a charm. Thank you👌😁
